### ISSUE TITLE
Question related to the equivariance

### ISSUE THREAD

**Issue by Frankie123421** [ehoogeboom/e3_diffusion_for_molecules#17]
Hi, nice work and thanks for sharing the code. I notice that the training process of EDM is computing the L2 loss of the sampled $\epsilon$ (subtract center of gravity) and predicted one, i.e., $\hat{\epsilon}=\phi(z_t, t)$ from the model. The latter one is actually computed as velocity (and also subtract center of gravity). I can see that $\hat{\epsilon}$ is equivaraint to $z_t$, but as mentioned in another work "Geodiff"([https://arxiv.org/abs/2203.02923](url)), we should also hope that $\epsilon$ is also equivaraint to $z_t$. I wonder if you consider this alignment problem since it is not mentioned in the paper. If I miss something, please let me know!!

**Comment by ehoogeboom** [comment]
Hi,

No alignment seemed to be necessary in our case. I'm not sure if it's needed in the case of geodiff. 

Best,
Emiel
