### ISSUE TITLE
How many samples are generated in the GEOM-drugs experiment?

### ISSUE THREAD

**Issue by DongkiKim95** [ehoogeboom/e3_diffusion_for_molecules#19]
Hello, I am enjoying your paper, and thank for your nice work!

I have a minor question.
How many samples are generated in the GEOM-drugs experiment (Table 4)?
Is it 10000 like the QM9 experiment?

**Comment by ehoogeboom** [comment]
Jep, those samples are in this repo somewhere, together with the python analyze file.
