### ISSUE TITLE
Trained model available?

### ISSUE THREAD

**Issue by hjuinj** [ehoogeboom/e3_diffusion_for_molecules#2]
Hi, 

Thank you for this work. I am wondering if you will release the trained GEOM EDM model in the future?

**Comment by ehoogeboom** [comment]
It is located here: https://github.com/ehoogeboom/e3_diffusion_for_molecules/tree/main/outputs/edm_geom_drugs

**Comment by hjuinj** [comment]
thank you, would it be possible for you to describe how I can try the GEOM EDM model to generate conformers for a set of molecules of my choice (not in the GEOM or QM9 set)?

**Comment by ehoogeboom** [comment]
Sorry I missed this message, yes it might be possible but you would have to do something as given here (see the discussion https://github.com/ehoogeboom/e3_diffusion_for_molecules/issues/3)


Alternatively, you might be looking for a model just for conformation generation, such as GeoDiff. Those models take in the molecular graph as input, and generate possible conformations for them.
