### ISSUE TITLE
Train on custom dataset

### ISSUE THREAD

**Issue by zhenzey** [ehoogeboom/e3_diffusion_for_molecules#20]
Thanks for sharing the code! I was wondering whether it is possible to train the diffusion model on our own graph dataset? If so, can you provide an example?

**Comment by tuln128** [comment]
Hello @zhenzey 
I have not tried the whole process yet, but I think you can follow the instructions on preparing the GEOM-Drugs dataset (https://github.com/ehoogeboom/e3_diffusion_for_molecules/tree/main/data/geom) to figure out how to make customized data usable in the framework.
Hope it helps,

**Comment by sevencheung2021** [comment]
> 

Hello, I also want to train on my own dataset, I would like to know if you have succeeded in training this model on your own dataset?

**Comment by sevencheung2021** [comment]
> Thanks for sharing the code! I was wondering whether it is possible to train the diffusion model on our own graph dataset? If so, can you provide an example?

Hello, I also want to train on my own dataset, I would like to know if you have succeeded in training this model on your own dataset?

**Comment by ehoogeboom** [comment]
Definitely possible, should not be crazy complicated. Unfortunately I don't have time to write supporting code/documentation for this.
