### ISSUE TITLE
Path to pretrained QM9 property classifiers is missing

### ISSUE THREAD

**Issue by amorehead** [ehoogeboom/e3_diffusion_for_molecules#21]
Hello. Thank you for sharing this great work with us all.

I noticed, after looking at the end of your `README.md`, that you are offering pretrained QM9 property classifier models within this repository. However, the path you specified at the end of the README does not exist, at least in the `main` branch for this project.

```
qm9/property_prediction/outputs/exp_class_alpha_pretrained
```

May I ask where we might find these checkpoints?

**Comment by amorehead** [comment]
For those interested in downloading trained checkpoints for the property classifier models described in the EDM manuscript, I have trained each of these six models and uploaded them to Zenodo in the record here: https://zenodo.org/record/7647653. I hope this helps!

**Comment by ehoogeboom** [comment]
Thanks retraining those models. I think the alpha one should be in exp_35_conditional_nf192_9l_alpha. Regardless thanks a lot.
