### ISSUE TITLE
Question regarding the dimension of QM9 and input to property classifier

### ISSUE THREAD

**Issue by yogeshverma1998** [ehoogeboom/e3_diffusion_for_molecules#22]
Hi,

I have a question about the number of maximum atoms used for QM9 generation. The maximum number of atoms for the QM9 dataset is 9, but when running the code, it used (29,5) as input to the property classifier, Can you let me know where are the extra entires coming from?

Also, do you transform your predicted coordinates or other things from EDM before inputting them into the property classifier and How?

Regards,
Yogesh

**Comment by amorehead** [comment]
I may be wrong here, but I believe `5` is the number of atom types in the GEOM-Drugs dataset (possibly a coincidence, or maybe not). If you are not secretly evaluating your models on the GEOM-Drugs dataset, I'm not sure where this `5` would be coming from.

**Comment by tuln128** [comment]
According to the codes for preprocessing input data (the _extract_conformer_ function, https://github.com/ehoogeboom/e3_diffusion_for_molecules/blob/main/build_geom_dataset.py), I have figured out, in this case, that:

- 29 is the number of atoms of the corresponding conformer in the input data

- 5 is the number of features associated with each conformer, in which the first one is the conformer's _id_ (just an increasing number), the second one is the _atomic number_ of each atom belonging to the conformer, and the last three ones are the 3D coordinates (_xyz_) of the atom.

Hope it helps.
