### ISSUE TITLE
Turning off equivariance?

### ISSUE THREAD

**Issue by MilesCranmer** [ehoogeboom/e3_diffusion_for_molecules#25]
Hi @ehoogeboom,
Great project! I am interested in trying it on an astronomy problem. Here, we have a point cloud of particles, but we don't care about their positions – only their properties. Therefore, I was wondering if there is a way I can turn off the equivariance module? i.e., only generate particles and their features, without worrying about their positions?
Thanks!
Miles

**Comment by ehoogeboom** [comment]
Think I answered this somewhere in email at some point, closing. Feel free to reopen if mistaken

**Comment by MilesCranmer** [comment]
I think you did, yes. But it might also be useful if you paste your answer here, as then it will be indexed by google rather than hidden in our email convo.

**Comment by Ala1s** [comment]
@MilesCranmer @ehoogeboom could you please share how to turn off equivariance, I would like to apply this model for my use case, where I also don't need equivariance

**Comment by sandipgiri576** [comment]
> I think you did, yes. But it might also be useful if you paste your answer here, as then it will be indexed by Google rather than hidden in our email convo.

 @MilesCranmer @ehoogeboom @Ala1s  Could you please share this? I also want to use this in my case. Mail ID: sg.chem4@kgpian.iitkgp.ac.in
