### ISSUE TITLE
Question about the code

### ISSUE THREAD

**Issue by 545487677** [ehoogeboom/e3_diffusion_for_molecules#27]
Hi,
Thank you for sharing such a great work. I am a little confused about this line of the code.  Can you tell me the role of delta_log_px in this line of the code and I don’t know why it times np.log(self.norm_values[0])?  
Thank you for sharing this work.  I genuinely appreciate the effort you've put into this work and would be grateful for your guidance.

Thank you.

 
 
https://github.com/ehoogeboom/e3_diffusion_for_molecules/blob/fce07d701a2d2340f3522df588832c2c0f7e044a/equivariant_diffusion/en_diffusion.py#L344

**Comment by ehoogeboom** [comment]
Hi

If you normalise data, you need to account for probability change via the change-of-variables formula.
