### ISSUE TITLE
Training Split for G-SchNet

### ISSUE THREAD

**Issue by ameya98** [ehoogeboom/e3_diffusion_for_molecules#28]
Hi, was the G-SchNet model used to generate samples here trained on the same data-split? The original paper only used 50k training samples.

**Comment by pearl-rabbit** [comment]
Hi, I also have a question about the G-Schnet model. I sampled 10,000 molecules using the pre-trained model given by G-Schnet and evaluated it using the metrics of this paper, and the results for validity and uniqueness are >95%. Do you know the reason for this, please?

**Comment by ehoogeboom** [comment]
@ameya98 we used the one as defined in the paper, that might be different than g-schnet.
@pearl-rabbit the samples from gschnet we used (and the corresponding python analyze file) are both in this repo
