### ISSUE TITLE
question regarding generation

### ISSUE THREAD

**Issue by orgw** [ehoogeboom/e3_diffusion_for_molecules#3]
Hi, thanks for the awesome paper

I was wondering if i can generate a molecule by inserting Zt(coordinates, atom types etc) instead of sampling Zt?

**Comment by ehoogeboom** [comment]
Hi, thank you for the compliment :). To answer your question possibly you could. It depends a bit on what you would want. I’ll give two examples;

1) You could for example insert an existing molecule at an early timestep (say for z_200, when the maximum is T=1000). The model would then refine the molecule.

2) Another option is to rewrite part of zt at each step during generation (for instance some/all positions in zt). Then the model could figure out the other stuff. 

For these examples, it’s currently unknown how the model will act and so interesting research. Perhaps it is interesting to look at the paper where they show “SDEdit” which does something a bit related to this but on images.

**Comment by orgw** [comment]
Thank you for your kind response! I got interested in diffusion models from reading your paper.

I am new to this field, and don't know a lot. If i may ask one more question: can I know how equation 19 is derived from equation 16?

**Comment by orgw** [comment]
Thanks!!
