### ISSUE TITLE
Explicit valence error in training

### ISSUE THREAD

**Issue by lajictw** [ehoogeboom/e3_diffusion_for_molecules#32]
Hi! I met a problem in training. The codes works super fine in the 0th epoch. But when it came to the 1st epoch, it pumped out explicit error for atoms. Two screenshots of the run have been attached below. Thanks for your help!
![image](https://github.com/ehoogeboom/e3_diffusion_for_molecules/assets/40271784/c953a053-9b10-42be-be25-4cdede4f87f0)
![image](https://github.com/ehoogeboom/e3_diffusion_for_molecules/assets/40271784/d5dd1705-0c62-4a37-aa85-a38d23817462)

**Comment by ehoogeboom** [comment]
It's been a while, but I think this is just something in eval that's part of the SMILES conversion. SMILES validity is kind of a tricky benchmark anyway, because it solves a lot of things that are incorrect.
