### ISSUE TITLE
Request for Release of Pre-trained Model Checkpoints

### ISSUE THREAD

**Issue by yanliang3612** [ehoogeboom/e3_diffusion_for_molecules#34]
Hello Authors,

I hope this message finds you well. I am writing to inquire about the possibility of releasing the checkpoints for the pre-trained models associated with this repository.

As an enthusiast and practitioner in the field, I've been greatly impressed by the work done in this project. The models you've developed have the potential to significantly aid in various applications and research. However, to fully leverage these models, having access to the pre-trained checkpoints would be immensely beneficial.

Understanding that there might be constraints or reasons for not having released them yet, I am curious to know if there are any plans to make these checkpoints available in the near future. If there are specific conditions or guidelines that must be met for their release, I would be more than willing to discuss or comply with them.

Thank you for considering this request. Your work is greatly appreciated by the community, and having access to these resources would be invaluable.

Looking forward to your response.

Best regards,
Divin

**Comment by ehoogeboom** [comment]
Some pretained checkpoints are available here:
https://github.com/ehoogeboom/e3_diffusion_for_molecules/tree/main/outputs
