### ISSUE TITLE
Inquiry Regarding the Creation of the qm9_second_half Dataset

### ISSUE THREAD

**Issue by yanliang3612** [ehoogeboom/e3_diffusion_for_molecules#35]
Hi,

I am currently studying your work presented in the EDM paper and am particularly interested in the qm9_second_half dataset. Could you please share insights on how this dataset was created? Understanding its creation process is crucial for my research.

Thank you for your time and assistance.

Best regards,

Divin

**Comment by ehoogeboom** [comment]
In our paper section 5.2 might help, and it could also help reach out to Victor directly, he created the dataset.
