### ISSUE TITLE
Training time for QM9?

### ISSUE THREAD

**Issue by sudarshan1994** [ehoogeboom/e3_diffusion_for_molecules#36]
How long does it take to run the QM9 experiment, with a n_epochs=3000, and batch size =64, It seems like it will take multiple days, are any of these hyperparameters wrong?

**Comment by ehoogeboom** [comment]
that could be reasonable depending on hardware

**Comment by sudarshan1994** [comment]
Thank you for your response, how many days does it take on your device? could you share how many seconds per epoch and what GPU you use?
