### ISSUE TITLE
aromatic bonds??

### ISSUE THREAD

**Issue by orgw** [ehoogeboom/e3_diffusion_for_molecules#5]
Hi,

may i ask the proportion of aromatic compounds during generation? I find difficulty generating aromatic compounds

Thanks

**Comment by ehoogeboom** [comment]
Hi,

we never explicitly checked for the number of aromatic molecules that are generated, so I am unsure whether it differs from the percentage found in training data. You could always try to train the model more on the aromatic molecules by increasing the frequency in which they occur during training
