### ISSUE TITLE
Question about the paper

### ISSUE THREAD

**Issue by Frankie123421** [ehoogeboom/e3_diffusion_for_molecules#8]
Hi, I am studying your nice work these days. And I am confused with a little bit foolish question: the paper mentioned that "it is impossible to have a non-zero distribution that is invariant to translations, since it cannot integrate to one", could you please explain further mathematically on why it cannot integrate to one?

**Comment by ehoogeboom** [comment]
Hi,

Let’s consider a 1d example. We meant that if p(x + t) = p(x), then it is constant so when we let p(x) = c then:

integral_-infty^+infty p(x) = integral_-infty^+infty c 
Which can either equal zero or tend towards plus/minus infinity.

**Comment by Frankie123421** [comment]
Thanks for your kind reply. I got it.
